id = "kukicha"
name = "Kukicha"
version = "0.2.0"
schema_version = 1
authors = ["Kukicha Contributors"]
description = "Kukicha language support with LSP - a beginner-friendly language that compiles to Go"
repository = "https://github.com/duber000/kukicha"

[grammars.kukicha]
repository = "./grammars/kukicha"
rev = "28bf5e67f2aa9ca5db85a3dc2ecbb23f174de254"

[language_servers.kukicha-lsp]
name = "Kukicha Language Server"
languages = ["Kukicha"]
