name = "Kukicha"
grammar = "kukicha"
path_suffixes = ["kuki"]
line_comments = ["# "]
tab_size = 4
hard_tabs = false
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]
